config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: "top_pages#index"
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'following'
      get 'follower'
    end
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:new, :create, :destroy, :edit, :update] do
    resources :watches, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :messages, only:[:index, :create, :destroy]
    resources :distances, only: [:create]
    resources :events, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only:[:index, :create, :destroy]
  def index
    room_ids = current_user.rooms.ids
    @rooms = Room.where(id: room_ids)
    @messages = @room.messages.includes(:user).order(id: "DESC")
    
    current_room = Room.find_by(public_uid: params[:room_id])
    @current_room_users = current_room.users
    unless @current_room_users.ids.include?(current_user.id)
      redirect_to rooms_path
    end
  end

  def create
    message = Message.create(message_params)
    render json:{ post: message, user: message.user }
  end

  def destroy
    message = Message.find(params[:id])
    if message.user.id == current_user.id
      message.destroy
      redirect_to room_messages_path(@room.public_uid)
    else
      render :index
    end
  end

  private

  def message_params
    params.permit(:content).merge(user_id: current_user.id, room_id: @room.id)
  end

  def set_user
    @room = Room.find_by(public_uid: params[:room_id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_main.html.erb
<div class="top-menu" id=<%@room.id%>>
  <div class="menu-roomname">
    <%= @room.thread_name %>
  </div>
  <div class="menu-lots"> 
    <%= link_to image_tag("edit.png", class: "room-edit"), edit_room_path(@room.public_uid) %>
  </div>
</div>
<div id="main-message">
  <div id="list">
  </div>
  <% @messages.each do |message| %>
    <% if message.user.id != current_user.id %>
      <div class="message">
        <div class="message-info">
          <p class="info-user"><%= link_to message.user.username, user_path(message.user.public_uid), class: "info-username" %></p>
        </div>
        <div class="message-contents">
          <div class="message-content">
            <%= safe_join(message.content.split("\n"), tag(:br)) %>
          </div>
          <div class="message-date">
            <p class="info-date"><%= l message.created_at, format: :short %></p>
          </div>
        </div>
      </div>
    <% else %>
      <div class="message-current-user">
        <div class="message-info">
          <p class="info-current-user"><%= link_to message.user.username, user_path(message.user.public_uid), class: "info-username" %></p>
        </div>
        <div class="current-user-message-contents">
          <div class="message-date">
            <p class="current-user-info-date"><%= l message.created_at, format: :short %></p>
          </div>
          <div class="current-user-message-content">
            <%= safe_join(message.content.split("\n"), tag(:br)) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<div class="send-enter">
  <%= form_with url: room_messages_path(@room.public_uid), method: :post, id: "send-form", local: true do |f| %>
    <%= f.text_area :content, id: "send-input", placeholder: "type a message or time" %>
    <%= f.submit '送信', id: "submit" %>
  <% end %>
</div>

app/views/messages/_right.html.erb
<div class="users-index">
  <h1>ユーザー一覧</h1>
  <% @current_room_users.each do |user| %>
    <div class="each-user-index">
      <%= link_to "#{user.username}", user_path(user.public_uid), class: "each-user" %>
    </div>
  <% end %>
  <p>計 <%= @current_room_users.count %>人</p>
</div>

app/views/messages/index.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render "shared/side_bar.html.erb" %>
  </div>

  <div class="main">
    <%= render "main.html.erb" %>
  </div>

  <div class="right-side">
    <%= render "right.html.erb" %>
  </div>
</div>