config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: "top_pages#index"
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'following'
      get 'follower'
    end
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:new, :create, :destroy, :edit, :update] do
    resources :watches, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :messages, only:[:index, :create, :destroy]
    resources :distances, only: [:create]
    resources :events, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  EMAIL_REGEX = /@.+/.freeze

  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :watches, dependent: :destroy
  has_many :sns_credentials

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  validates :username, presence: true
  validates_format_of :email, with: EMAIL_REGEX

  generate_public_uid

  def to_param
    public_uid
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(search)
    if search != ""
      User.where('username LIKE(?)', "%#{search}%")
    end
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first
    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        username: "",
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    return { user: user ,sns: sns}
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        username: "",
        email: auth.info.email,
      )
    end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else 
      @sns = info[:sns]
      render template: "devise/registrations/new" 
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    if params[:sns_auth] == "true"
      pass = Devise.friendly_token.first(8)
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :follower]
  before_action :side_menu, only: [:show, :edit, :following, :follower, :search]
  def show
    @following = Relationship.where(user_id: @user.id).count
    @follower = Relationship.where(follow_id: @user.id).count
    @watches = Watch.where(user_id: @user.id)
  end

  def edit
    unless current_user.public_uid == @user.public_uid
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.public_uid)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to new_user_registration_path
    else
      render :show
    end
  end

  def following
    followings = User.find(@user.id).following_ids
    @users = User.where(id: followings)
    @comment = "フォロー"
  end

  def follower
    followers = User.find(@user.id).follower_ids
    @users = User.where(id: followers)
    @comment = "フォロワー"
  end

  def search
    if params[:keyword] != ""
      @users = User.search(params[:keyword])
    else
      flash[:search] = "※入力してください"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :introduction)
  end

  def set_user
    @user = User.find_by(public_uid: params[:id])
  end

  def side_menu
    room_ids = current_user.rooms.ids
    @rooms = Room.where(id: room_ids)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_follower_lists.html.erb
<div class="follow-or-follower-lists">
  <h1><%= @comment %>一覧</h1>
  <div class="follow-or-follower-users-list">
    <% unless @users == [] %>
      <% @users.each do |user| %>
        <div class="following-lists">
          <%= link_to user_path(user.public_uid), class: "users-path" do %>
            <div class='users-path-info'>
              <h3><%= user.username %></h3>
              <p><%= user.followings.count %>フォロー/<%= user.followers.count %>フォロワー</p>
            </div>
            <% if user.introduction %>
              <p><%= user.introduction %></p>
            <% else %>
              <p>No introduction</p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p class="no-user"><%= @comment %>はいません</p>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render "shared/side_bar.html.erb" %>
  </div>
  <div class="main">
    <div class="user-infomation">
      <div class="infomation-user">
        <h1>ユーザー情報</h1>

        <div class="user-identification-info">
          <h3>ID</h3>
          <%= @user.public_uid %>
        </div>

        <%= form_with url: user_path(@user.public_uid), method: :patch, model: @user, local: true do |f| %>
          <div class="user-identification-info">
            <h3>ユーザー名</h3>
            <%= f.text_field :username, class: "username-edit" %>
          </div>

          <div class="user-identification-introduction">
            <h3>自己紹介：</h3>
            <%= f.text_area :introduction, class: "introduction-edit" %>
          </div>
          <div class="user-edit-buttons">
            <%= f.submit "更新する", class: "user-identification-btn" %>
          </div>
        <% end %>
      </div>
      <div class="user-info-destroy">
        <%= link_to "アカウント削除", user_path(@user.public_uid), method: :delete, class: "user-destroy btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/users/follower.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render 'shared/side_bar.html.erb' %>
  </div>
  <div class="main">
    <%= render 'follow_follower_lists.html.erb' %>
  </div>
</div>

app/views/users/following.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render 'shared/side_bar.html.erb' %>
  </div>
  <div class="main">
    <%= render 'follow_follower_lists.html.erb' %>
  </div>
</div>

app/views/users/search.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render "shared/side_bar.html.erb" %>
  </div>
  <div class="main">
    <div class="select-users">
      <h1>ユーザー一覧</h1>
      <div class="many-users">
        <% unless @users == [] %>
          <% @users.each do |user| %>
            <div class="result-user">
              <%= link_to user_path(user.public_uid), class: "users-path" do %>
                <div class='users-path-info'>
                  <h3><%= user.username %></h3>
                  <p><%= user.followings.count %>フォロー/<%= user.followers.count %>フォロワー</p>
                </div>
                <% if user.introduction %>
                  <p><%= user.introduction %></p>
                <% else %>
                  <p>No introduction</p>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p class="no-user">ユーザーはいません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render "shared/side_bar.html.erb" %>
  </div>
  <div class="main">
    <div class="user-infomation">
      <div class="infomation-user">
        <h1>ユーザー情報</h1>

        <div class="user-identification-info">
          <h3>ID</h3>
           <%= @user.public_uid %>
        </div>

        <div class="user-identification-info">
          <h3>ユーザー名</h3>
          <%= @user.username %>
        </div>

        <div class="user-identification-introduction">
          <h3>自己紹介：</h3>
          <% if @user.introduction %>
            <p><%= @user.introduction %></p>
          <% else %>
            <p>No introduction</p>
          <% end %>
        </div>

        <div class="follow-follower-lists">
          <%= link_to "#{@following}フォロー", following_user_path(@user.public_uid), class: "follow-follower users-link" %>
          <%= link_to "#{@follower}フォロワー", follower_user_path(@user.public_uid), class: "follow-follower users-link" %>
        </div>

        <%= render 'relationships/follow_button.html.erb' %>
        <div class="flash-message">
          <%= flash[:success] %>
          <%= flash[:alert] %>
        </div>
      </div>
    </div>
    <div class="users-table">
      <table>
        <thead>
          <tr>
            <th class="date">日付</th>
            <th class="time">タイム</th>
            <th class="event">種目</th>
            <th class="distance">距離</th>
          </tr>
        </thead>
        <tbody id="time-table">
          <% if @watches %>
            <% @watches.reverse_each do |watch| %>
              <tr id=<%= watch.id %>>
                <td class="date">
                  <%= watch.created_at.strftime('%Y/%m/%d') %>
                </td>
                <td class="time">
                  <%= watch.watch %>
                </td>
                <td class="event">
                  <% if watch.event_id %>
                    <%= watch.event.event %>
                  <% end %>
                </td>
                <td class="distance">
                  <% if watch.distance_id %>
                    <%= watch.distance.distance %>
                  <% end %>
                </td> 
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>