config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: "top_pages#index"
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'following'
      get 'follower'
    end
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:new, :create, :destroy, :edit, :update] do
    resources :watches, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :messages, only:[:index, :create, :destroy]
    resources :distances, only: [:create]
    resources :events, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/distance.rb
class Distance < ApplicationRecord
  has_one :watch

  validates :distance, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_one :watch

  validates :event, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :watches, dependent: :destroy

  validates :thread_name, presence: true

  generate_public_uid

  def to_param
    public_uid
  end
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  EMAIL_REGEX = /@.+/.freeze

  has_many :room_users, dependent: :destroy
  has_many :rooms, through: :room_users
  has_many :messages, dependent: :destroy
  has_many :watches, dependent: :destroy
  has_many :sns_credentials

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  validates :username, presence: true
  validates_format_of :email, with: EMAIL_REGEX

  generate_public_uid

  def to_param
    public_uid
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.search(search)
    if search != ""
      User.where('username LIKE(?)', "%#{search}%")
    end
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first
    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        username: "",
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    return { user: user ,sns: sns}
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        username: "",
        email: auth.info.email,
      )
    end
    return {user: user}
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    return { user: user ,sns: sns}
  end
end

app/models/watch.rb
class Watch < ApplicationRecord

  validates :watch, presence: true

  belongs_to :room
  belongs_to :user, optional: true
  belongs_to :event, optional: true
  belongs_to :distance, optional: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:new, :edit, :update]
  before_action :set_room, only: [:new, :edit]
  before_action :following_user, only: [:new, :create, :edit, :update]
  before_action :follower, only: [:new, :edit]

  def new
    @thread = Room.new
  end

  def create
    @room = Room.create(room_params)
    if @room.save
      redirect_to room_messages_path(@room.public_uid)
    else
      render :new
    end
  end

  def edit
    @users_in_this_room = @room.users
    @room = Room.find_by(public_uid: params[:id])
    @invite_users = @mutual_follow - @users_in_this_room
  end
  
  def update
    @users_in_this_room = @room.users
    @follow_users = @users.where.not(id: @users_in_this_room.ids)
    if @room.update(room_params)
      redirect_to room_messages_path(@room.public_uid)
    else
      render :edit
    end
  end

  def destroy
    room = Room.find_by(public_uid: params[:id])
    if room.destroy
      redirect_to rooms_path
    end
  end

  private
  
  def room_params
    params.require(:room).permit(:thread_name, :public_uid, user_ids: [])
  end

  def set_user
    @room = Room.find_by(public_uid: params[:id])
  end

  def set_room
    room_ids = current_user.rooms.ids
    @rooms = Room.where(id: room_ids)
  end

  def following_user
    @users = User.find(current_user.id).followings
  end

  def follower
    follower_users = User.find(current_user.id).followers
    @mutual_follow = @users & follower_users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :follower]
  before_action :side_menu, only: [:show, :edit, :following, :follower, :search]
  def show
    @following = Relationship.where(user_id: @user.id).count
    @follower = Relationship.where(follow_id: @user.id).count
    @watches = Watch.where(user_id: @user.id)
  end

  def edit
    unless current_user.public_uid == @user.public_uid
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.public_uid)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to new_user_registration_path
    else
      render :show
    end
  end

  def following
    followings = User.find(@user.id).following_ids
    @users = User.where(id: followings)
    @comment = "フォロー"
  end

  def follower
    followers = User.find(@user.id).follower_ids
    @users = User.where(id: followers)
    @comment = "フォロワー"
  end

  def search
    if params[:keyword] != ""
      @users = User.search(params[:keyword])
    else
      flash[:search] = "※入力してください"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :introduction)
  end

  def set_user
    @user = User.find_by(public_uid: params[:id])
  end

  def side_menu
    room_ids = current_user.rooms.ids
    @rooms = Room.where(id: room_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcTime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'shared/header' %>
        <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-messages">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="copyright">
    <p>© 2021 Hayato Oshima</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <%= link_to image_tag("logo.png", class:"icon"), "/" %>

  <% if user_signed_in? %>
    <div class="user-content">
      <%= link_to(current_user.username+"さん", user_path(current_user.public_uid), class: "username") %>
      <%= link_to("ログアウト", destroy_user_session_path, method: :delete, class: "log") %>
  </div>
  <% end %>
</header>

app/views/shared/_side_bar.html.erb
<div class="sidebar-menu">
  <div class="sidebar-threads">
    <%= image_tag "plus.png", alt: "スレッドを作成する", class: "sidebar-img" %>
    <%= link_to "スレッドを作成する", new_room_path, class: "sidebar-button" %>
  </div>
  <% unless current_page?(new_room_path) || request.path.include?("users") %>
    <div class="sidebar-threads">
      <%= image_tag "stopwatch.png", alt: "タイムを測る", class: "sidebar-img" %>
      <%= link_to "タイムを測る", new_room_watch_path(@room.public_uid), class: "sidebar-button" %>
    </div>
    <div class="sidebar-threads">
      <%= image_tag "time_registration.png", alt: "タイムを登録する", class: "sidebar-img" %>
      <%= link_to "タイムを登録する", room_watches_path(@room.public_uid), class: "sidebar-button" %>
    </div>
  <% end %>
  <div class="invisible-index">
    <div class="threads-index">  
      <%= image_tag "toggle.png", alt: "スレッド一覧", class: "sidebar-img" %>
      <h3>スレッド一覧</h3>
    </div>
    <div class="threads-ul">
      <ul>
        <% @rooms.each do |room| %>
          <li><a href="/rooms/<%=room.public_uid%>/messages" class="thread-name"><%= room.thread_name %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>