config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: "top_pages#index"
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'following'
      get 'follower'
    end
    collection do
      get 'search'
    end
  end
  resources :rooms, only: [:new, :create, :destroy, :edit, :update] do
    resources :watches, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :messages, only:[:index, :create, :destroy]
    resources :distances, only: [:create]
    resources :events, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/watch.rb
class Watch < ApplicationRecord

  validates :watch, presence: true

  belongs_to :room
  belongs_to :user, optional: true
  belongs_to :event, optional: true
  belongs_to :distance, optional: true
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_room, only: [:index, :new, :create, :update, :destroy]
  before_action :common_data, only: [:index, :new, :create]
  before_action :side_menu, only: [:index , :new]
  require 'csv'

  def index
  end

  def new
    @watches = Watch.includes(:user).where(room_id: @room.id).order(id: "DESC").page(params[:page]).per(50)
    unless @current_room_users.ids.include?(current_user.id)
      redirect_to rooms_path
    end
    respond_to do |format|
      format.html
      format.csv do |csv|
        watches = Watch.where(room_id: @room.id).order(id: "DESC")
        export_time_csv(watches)
      end
    end
  end

  def create
    watch = Watch.create(watch_params)
    if params[:event_id]
      if watch.save
        flash[:notice] = "正常に登録されました"
        redirect_to room_watches_path(@room.public_uid)
      else
        flash[:alert] = "正しい情報を入力して下さい"
        render :index
      end
    else
      render json:{ watch: watch, users: @users, events: @events, distances: @distances }
    end
  end

  def edit
  end

  def update
    watch = Watch.find(params[:id])
    watch.update(watch_params)
    render json:{ watch: watch }
  end

  def destroy
    watch = Watch.find(params[:id])
    if watch.destroy
      redirect_to new_room_watch_path(@room.public_uid)
    else
      render :new
    end
  end

  private
  
  def watch_params
    params.permit(:watch, :event_id, :distance_id, :user_id).merge(room_id: @room.id)
  end

  def set_room
    @room = Room.find_by(public_uid: params[:room_id])
  end

  def common_data
    @users = User.where(id: @room.user_ids)
    @events = Event.where(room_id: @room.id)
    @distances = Distance.where(room_id: @room.id)
  end

  def side_menu
    room_ids = current_user.rooms.ids
    @rooms = Room.where(id: room_ids)
    current_room = Room.find_by(public_uid: params[:room_id])
    @current_room_users = current_room.users
  end
  
  def export_time_csv(watches)
    csv_data = CSV.generate do |csv|
      column_names = %w(日付 タイム 名前 種目 距離)
      csv << column_names
      watches.each do |watch|
        if watch.user == nil
          username = ""
        else
          username = watch.user.username
        end
        if watch.event == nil
          event = ""
        else
          event = watch.event.event
        end
        if watch.distance == nil
          distance = ""
        else
          distance = watch.distance.distance
        end
        column_values = [
          watch.created_at.strftime('%Y/%m/%d'),
          watch.watch,
          username,
          event,
          distance
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: "タイム一覧.csv")
  end
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/watches/_right.html.erb
<%= render "messages/right.html.erb" %>
<div class="right-side-wrapper">
  <div class="right-each-registration">
    <h1>各種登録</h1>
    <p>種目登録</p>
    <%= form_with url: room_events_path(@room.public_uid), id: "event-form" do |f| %>
      <%= f.text_field :event, id: "event-input", class: "registration-input" %>
      <%= f.submit "登録", id: "event-registration", class: "registration-button" %>
    <% end %>
    <p>距離登録</p>
    <%= form_with url: room_distances_path(@room.public_uid), id: "distance-form" do |f| %>
      <%= f.text_field :distance, id: "distance-input", class: "registration-input" %>
      <%= f.submit "登録", id: "distance-registration", class: "registration-button" %>
    <% end %>
  </div>
  <div class="right-anywhere-path">
    <p><%= link_to "スレッドに戻る→", room_messages_path(@room.public_uid), class: "to-messages-path" %></p>
    <p><%= link_to "csvで出力する→", new_room_watch_path(format: :csv), class: "export-csv" %></p>
  </div>
</div>

app/views/watches/index.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render "shared/side_bar.html.erb" %>
  </div>
  <div class="main">
    <div class="user-registration">
      <h2>タイム新規登録</h2>
      <% if notice %>
        <div class="time-flash-notice time-flash">
          <%= notice %>
        </div>
      <% else %>
        <div class="time-flash-alert time-flash">
          <%= alert %>
        </div>
      <% end %>
      <%= form_with url: room_watches_path(@room.public_uid), method: :post, local: true do |f| %>

        <div class="field">
          <%= f.label :watch, "タイム", class: "label" %>
          <%= f.text_field :watch, placeholder: "00:00:00.000 形式で入力してください", class: "time-field registration-field" %>
        </div>

        <div class="field">
          <%= f.label :user_id, "ユーザー名", class: "label "%>
          <%= f.collection_select :user_id, @users, :id, :username, {prompt: "-----"}, {class: "pulldown-registration registration-field"} %>
        </div>

        <div class="field">
          <%= f.label :event_id, "種目", class: "label" %>
          <%= f.collection_select :event_id, @events, :id, :event, {prompt: "-----"}, {class: "pulldown-registration registration-field"} %>
        </div>

        <div class="field">
          <%= f.label :distance_id, "距離", class: "label" %>
          <%= f.collection_select :distance_id, @distances, :id, :distance, {prompt: "-----"}, {class: "pulldown-registration registration-field"} %>
        </div>

        <div class="actions">
          <%= f.submit "登録", class: "button" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="right-side">
    <%= render "right.html.erb" %>
  </div>
</div>

app/views/watches/new.html.erb
<div class="wrap">
  <div class="left-side">
    <%= render "shared/side_bar.html.erb" %>
  </div>

  <div class="main">
    <%# タイマーの時間表示 %>
    <div class="stop-watch">
      <p id="time">00:00:00.000</p>
    </div>

    <%# STARTとSTOPのボタン %>
    <%= form_with url: room_watches_path(@room.public_uid), class: "buttons" do |f| %>
      <%= f.submit "START", class: "btn", id: "start" %>
      <%= f.submit "LAP", class: "btn", id: "lap" %>
    <% end %>

    <div class="table">
      <table>
        <thead>
          <tr>
            <th class="date">日付</th>
            <th class="time">タイム</th>
            <th class="name">名前</th>
            <th class="event">種目</th>
            <th class="distance">距離</th>
            <th class="table-edit"></th>
          </tr>
        </thead>
        <tbody id="time-table">
          <% if @watches %>
            <% @watches.each do |watch| %>
              <tr id=<%= watch.id %>>
                <td class="date">
                  <%= watch.created_at.strftime('%Y/%m/%d') %>
                </td>
                <td class="time">
                  <%= watch.watch %>
                </td>
                <%= form_with url: room_watch_path(@room.public_uid, watch.id), method: :patch do |f| %>
                  <td class="name">
                    <% if watch.user_id %>
                      <%= f.collection_select :user_id, @users.where.not(id: watch.user.id), :id, :username, {prompt: "#{watch.user.username}"}, {class: "data-pulldown data-username"} %>
                    <% else %>
                      <%= f.collection_select :user_id, @users, :id, :username, {prompt: "-----"}, {class: "data-pulldown data-username"} %>
                    <% end %>
                  </td>
                  <td class="event">
                    <% if watch.event_id %>
                      <%= f.collection_select :event_id, @events.where.not(id: watch.event.id), :id, :event, {prompt: "#{watch.event.event}"}, {class: "data-pulldown data-event"} %>
                    <% else %>
                      <%= f.collection_select :event_id, @events, :id, :event, {prompt: "-----"}, {class: "data-pulldown data-event"} %>
                    <% end %>
                  </td>
                  <td class="distance">
                    <% if watch.distance_id %>
                      <%= f.collection_select :distance_id, @distances.where.not(id: watch.distance.id), :id, :distance, {prompt: "#{watch.distance.distance}"}, {class: "data-pulldown data-distance"} %>
                    <% else %>
                      <%= f.collection_select :distance_id, @distances, :id, :distance, {prompt: "-----"}, {class: "data-pulldown data-distance"} %>
                    <% end %>
                  </td> 
                <% end %>
                <td class="table-edit">
                  <%= link_to image_tag("/images/delete.png", class: "watch-delete"), room_watch_path(@room.public_uid, watch.id), method: :delete, data: {confirm: "本当に削除しますか？\n削除するとストップウォッチも止まります"} %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

    <% if @watches %>
      <%= paginate @watches %>
    <% end %>
  </div>
  
  <div class="right-side">
    <%= render "right.html.erb" %>
  </div>
</div>